### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by torstenkoepke** [larslockefeer/obsidian-plugin-todo#3]
Well done, I like this!

Some suggestions to make it even better:

- I don't know if this is possible at all, but it would be great to show the filename (e.g a project name) of the task when hovering over the link at the right of the task, or if this is not an option, to include the filename in another way, e.g. at the end of the lines
- For the tasks in the today tab, I would delete the #2021-02-19 to make the list less cluttered
- To reduce clutter even more, I would use #21-02-19, as trailing 20 is just useless, at least for the next 79 years
- The same holds in the someday tab, #someday can just be stripped out of the task
- How are the tasks sorted? I would think that by name of the source files would make some sense

**Comment by larslockefeer** [comment]
Hey @torstenkoepke, thanks for your suggestions!

> I don't know if this is possible at all, but it would be great to show the filename (e.g a project name) of the task when hovering over the link at the right of the task, or if this is not an option, to include the filename in another way, e.g. at the end of the lines

That sounds pretty easy to do, will consider this!

> How are the tasks sorted

Currently, tasks that have an "action date" are sorted by that date. Otherwise, there is no clear sorting yet; I was actually thinking to sort by modification date of the file that the task is found in, but that leads to tasks moving when you edit a file. Sorting by name of the source file is a nice suggestion.

As for your other suggestions: in a future release I definitely want to clean up the list view and remove (unnecessary) tags from the task description. It needs some more thinking but I plan to work on this.

**Comment by torstenkoepke** [comment]
Excellent Lars - thanks for all the time you put into this!
