### ISSUE TITLE
Question about Date (tag) format

### ISSUE THREAD

**Issue by rolfaalders** [larslockefeer/obsidian-plugin-todo#51]
Non tech guy here... 
I'd like to set the date format to "yyyymmdd" but when I put this in the date format field I get an error message "Error: Invalid date format"

The description next to 'Date format' states; Must include the %date% token, 
The prefilled value is yyyy-MM-dd, which doesn't include the %date% value either. When I replace yyyy-MM-dd with yyyymmdd the error shows...

I didn't change the Date tag format field. 
Please advice

**Comment by larslockefeer** [comment]
Hey @rolfaalders, to get the desired date format you can replace the standard `yyyy-MM-dd` Date format with `yyyyMMdd`. Note the all-caps `M`s, this is important.

High-level, the way this works is as follows:
- There is a piece of code that looks at the description of each tasks and tries to extract a date from it
- With the "Date format" setting, you can tell that piece of code the format of the date to look for
- This is done by way of "tokens", each token represents a date part in a specific format. `yyyy` stands for a four-digit representation of the year, `MM` for a two-digit representation of the month including leading zeroes etc. For a full overview of the supported tokens, see [here](https://moment.github.io/luxon/#/formatting?id=table-of-tokens).

The invalid date format error occurs because `mm` is a token that represents time (minutes including leading zeroes) instead of a date.

The setting for Date tag format can be left as is (`#%date%`). If desired, you can use this setting to change the marker that represents a due date. With the default setting, you can add due dates to tasks by prefixing the date with a `#` sign. But different workflows have different preferences.

I for example use `[due: 2022-01-20]`, so my settings are:
- Date tag format `[due: %date%]`
- Date format `yyyy-MM-dd`

Hope this helps!

**Comment by rolfaalders** [comment]
Solved. That fixed my question. 
First of all, I indeed used lower case 'mm'.
But I also used the 'prefix' in the note wrong. 
In the screenshots I saw [due::  .....] so I figured that is the default way of setting the due date.
In the settings I saw #%date%, but figured that didn't need to be changed and using the [due:: tigger was fine...
Perhaps replacing the screenshots to match the default setting?

Thanks man! :)

**Comment by larslockefeer** [comment]
Good point 😄  The screenshots are confusing. I'll replace them and then close this issue afterwards. Thanks for reporting!

**Comment by bgriffen** [comment]
Indeed, took me forever to find out that the screenshots are not the default date format Thanks!

**Comment by larslockefeer** [comment]
I replaced the screenshots. Thanks again for reporting!
